version: 0.4.6.{build}
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build_script:
- cmd: >-
    git submodule update --init --recursive

    cd Source

    msbuild Myra.sln /p:Configuration=Release /t:rebuild

    msbuild Myra.Installer.sln /p:Configuration=Release /t:rebuild

    set "INSTALLER_PATH=C:\projects\myra\Source\Myra.Installer\bin\Release\Myra.%APPVEYOR_BUILD_VERSION%.msi"

    echo "%INSTALLER_PATH%"

    copy "C:\projects\myra\Source\Myra.Installer\bin\Release\Myra.Installer.msi" "%INSTALLER_PATH%"

    nuget pack Myra\Myra.nuspec -Version %APPVEYOR_BUILD_VERSION%

    nuget pack Myra.Editor\Myra.Editor.nuspec -Version %APPVEYOR_BUILD_VERSION%

    copy_zip_package_files.bat
    
    rename "ZipPackage" "Myra.%APPVEYOR_BUILD_VERSION%"
    
    7z a Myra.%APPVEYOR_BUILD_VERSION%.zip Myra.%APPVEYOR_BUILD_VERSION%
artifacts:
  - path: Source/Myra.$(appveyor_build_version).nupkg
    name: Myra.nupkg

  - path: Source/Myra.Editor.$(appveyor_build_version).nupkg
    name: Myra.Editor.nupkg

  - path: Source/Myra.$(appveyor_build_version).zip
    name: ZipPackage

  - path: Source/Myra.Installer/bin/Release/Myra.$(appveyor_build_version).msi
    name: MsiPackage